import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,validateTree,evaluate,questionsFor,clone,demoTree} from '../dist/engine.js';
import {migrateTree,connections,removeConnection,layoutTree} from '../dist/graph-model.js';
function sumFixture(){const [a,b]=initialState({demo:true}).profiles;a.tree={start:'sum',nodes:[{id:'sum',type:'sum',label:'Total',inputs:['s1','s2'],threshold:14,yes:'yes',no:'no',x:0,y:0},...['s1','s2'].map(id=>({id,key:id,type:'scale',label:id,mode:'input',min:1,max:10,ranges:[{min:1,max:10,to:''}],x:0,y:0})),...['yes','no'].map(id=>({id,type:'terminal',label:id,outcome:id==='yes'?'match':'reject',x:0,y:0}))]};b.answers={s1:7,s2:7};return [a,b];}
test('sum is strictly greater, waits for both scores, and prompts scalar questions',()=>{const [a,b]=sumFixture();assert.deepEqual(validateTree(a.tree),[]);assert.equal(evaluate(a.tree,a,b).status,'reject');b.answers.s2=8;assert.equal(evaluate(a.tree,a,b).status,'match');delete b.answers.s2;assert.equal(evaluate(a.tree,a,b).status,'pending');assert.deepEqual(questionsFor(a,b).filter(q=>q.needed).map(q=>q.id),['s2']);});
test('typed slots reject binary scores, duplicated inputs and flow into input-only questions',()=>{const [a]=sumFixture();a.tree.nodes[1].type='boolean';assert.ok(validateTree(a.tree).some(e=>e.includes('scale')));a.tree.nodes[1].type='scale';a.tree.nodes[0].inputs=['s1','s1'];assert.ok(validateTree(a.tree).some(e=>e.includes('different')));a.tree.nodes[0].inputs=['s1','s2'];a.tree.nodes[0].yes='s1';assert.ok(validateTree(a.tree).some(e=>e.includes('input-only')));});
test('deleting flow and data edges leaves a saveable draft',()=>{const [a]=sumFixture();for(const edge of connections(a.tree))removeConnection(a.tree,edge);assert.deepEqual(validateTree(a.tree,{allowUnconnected:true}),[]);assert.ok(validateTree(a.tree).length);assert.equal(connections(a.tree).length,0);});
test('migration keeps custom labels and keys and is idempotent',()=>{const t=demoTree();t.nodes[0].label='Do they shower daily?';migrateTree(t);assert.equal(t.nodes[0].label,'Do they shower daily?');assert.deepEqual(t.nodes.find(n=>n.type==='count').inputs.map(id=>t.nodes.find(n=>n.id===id).key),['curious','funny','ambitious']);const before=clone(t);migrateTree(t);assert.deepEqual(t,before);});
test('cleanup preserves graph semantics and spaces nodes without overlap',()=>{const [a,b]=initialState({demo:true}).profiles;const before=connections(a.tree),result=evaluate(a.tree,a,b);layoutTree(a.tree);assert.deepEqual(connections(a.tree),before);assert.deepEqual(evaluate(a.tree,a,b),result);for(const n of a.tree.nodes.filter(n=>n.mode!=='input'))for(const m of a.tree.nodes.filter(n=>n.mode!=='input'))if(n!==m){const h=n.type==='count'?120+n.inputs.length*65:120;assert.ok(n.x+260<=m.x||m.x+260<=n.x||n.y+h<=m.y||m.y+(m.type==='count'?120+m.inputs.length*65:120)<=n.y)};});
